config/routes.rb
Rails.application.routes.draw do

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :projects do
    get '/author' => 'projects#get_project_author'
    resources :comments, only: [:index,:create, :update, :destroy]    
  end

  namespace :admin do
    resources :projects, :comments, :users
  end
  

  
end

app/models/admin.rb
class Admin < ApplicationRecord
    devise :database_authenticatable, :timeoutable   
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :commentable, polymorphic: true
    belongs_to :user

    validates :content, presence: true, allow_blank: false
end
  
  

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :comments, as: :commentable
    
    validates :name, presence: true, allow_blank: false
    scope :published, -> { where(privacy: 'public') }    
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  has_many :projects
  has_many :comments, dependent: :destroy
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end
  
  def is_admin?
    Admin.exists? user_id: self.id #=> 1 or nil
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
    before_action :authenticate_user!
    def authorized?
        #check if authorized here.
        unless current_user.is_admin?
            redirect_to projects_path
        end
    end    
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
    before_action :authorized?
    before_action :set_comment, only: [:update, :edit, :destroy]
    
    def index
        @comments = Comment.all
    end

    def edit

    end
    
    def update
        @comment.update(params.permit(:content))
        redirect_to admin_comments_path
    end

    def destroy
        @comment.destroy
        redirect_to admin_comments_path        
    end
    
    private
    def set_comment
        @comment = Comment.find(params[:id])
    end

    
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
    before_action :authorized?
    before_action :set_project, only: [:update, :edit, :destroy]
    
    def index
        @projects = Project.all
    end

    def edit

    end
    
    def update
        @project.update(params.permit(:name, :description, :privacy, :est_effort, :act_effort, :status))
        redirect_to admin_projects_path
    end

    def destroy
        @project.destroy
        redirect_to admin_projects_path        
    end
    
    private
    def set_project
        @project = Project.find(params[:id])
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
    before_action :authorized?
    before_action :set_user, only: [:update, :edit, :destroy]
    
    def index
        @users = User.all
    end

    def edit

    end
    

    def destroy
        @user.destroy
        redirect_to admin_users_path        
    end
    
    private
    def set_user
        @user = User.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ReactOnRails::Controller

  def after_sign_in_path_for
    projects_path
  end


  def load_commentable
    resource, id = request.path.split('/')[1,2]
    unless @commentable = resource.singularize.classify.constantize.find_by_id(id)
      render_404
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!    
  before_action :load_commentable
  include JsonParser
  
  def create
    content = parse(params['payload'])
    comment = @commentable.comments.build(content: content, user_id: current_user.id)
    comment.save
    comment_json = comment.as_json
    comment_json[:user] = {name: comment.user.name}
    render json: comment_json, stauts: :ok
  end

  def index
    comments = @commentable.comments.includes(:user)
    comments_json = comments.as_json(include: {user:{ only: [:name]}})
    render json: comments_json, status: :ok
  end

end

app/controllers/concerns/json_parser.rb
module JsonParser
  
  
    def parse(string)
        hash = JSON.parse string        
    end

  end

app/controllers/concerns/response.rb
module Response
    def json_response(object, status = :ok)
        render json: object, status: status
    end

    def error_response(object,status = :bad_request)
        if object.nil?
            render nothing: true, status: status            
        else
            render json: object.errors.messages.flatten.join(', '), status: status
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


    def index
        if current_user
            redirect_to projects_path and return
        end
    end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])
    
        if @user.persisted?
          bypass_sign_in @user
          redirect_to projects_path
          set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
        else
          session["devise.facebook_data"] = request.env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    
      def failure
        redirect_to root_path
      end
end    

app/controllers/projects_controller.rb
    class ProjectsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_project, only: [:update, :edit]
    before_action :check_owner, only: [:edit]
    include JsonParser
    include Response
    def index
        @projects_json = {projects: Project.published.as_json}
    end

    def create
        new_project = current_user.projects.create(project_params)
        if new_project.save
            json_response(new_project)
        else          
            error_response(new_project)
        end
    end

    def edit
    end

    def update
        if @project.user.id != current_user.id
            render status: :unauthorized, text: 'You cannot edit this project.' and return
        end
        new_params = project_params
        @project.update(new_params)
        render status: :ok, nothing: true
    end

    def get_project_author
        unless project = Project.find_by_id(params[:project_id])
            error_response(project) and return           
        end            
        unless user = project.user
            error_response(user) and return           
        end
        json_response(user)        
    end

    private
        def project_params
            new_params = ActionController::Parameters.new(parse(params['payload']))
            parsed_params = new_params.permit(:name, :description, :privacy, :est_effort, :act_effort, :status)
        end

        def set_project
            @project = Project.find(params[:id])
        end

        def check_owner
            if @project.user.id != current_user.id
                flash[:alert] = 'You have no access to that.'
                redirect_to projects_path
            end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/comments/edit.html.erb
<div class="self-centering" style="max-width:800px; margin-top:30px;">
    <%= form_tag(admin_comment_path(@comment), method: :put) do %>

      <div>
        <%= label_tag :content %>
        <%= text_field_tag :content, @comment.content %>
      </div>

      <%= submit_tag "Save" %>
    <% end %>
</div>

app/views/admin/comments/index.html.erb
  <h1>Comments</h1>
  <br>
  <table>
    <thead>
      <tr>
        <th >User</th>
        <th >content</th>
        <th >Model</th>
        <th >Created</th>
        <th >Delete?</th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td class="table-space"><%= comment.user.name %></td>
          <td class="table-space"><%= link_to comment.content, edit_admin_comment_path(comment) %></td>
          <td class="table-space"><%= comment.commentable_type %></td>
          <td class="table-space"><%= comment.created_at%></td>
          <td class="table-space">
          <%= form_tag(admin_comment_path(comment), method: :DELETE) do %>
                  <%= submit_tag "Delete" %>
          <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>  
</div>

app/views/admin/projects/edit.html.erb
<div class="self-centering" style="max-width:800px; margin-top:30px;">
    <%= form_tag(admin_project_path(@project), method: :put) do %>

      <div>
        <%= label_tag :name %>
        <%= text_field_tag :name, @project.name %>
      </div>
      <div>
        <%= label_tag :description %>
        <%= text_field_tag :description, @project.description %>
      </div>
      <div>
        <%= label_tag :type %>
        <%=select_tag "privacy", options_for_select([ "private", "public" ], @project.privacy) %>
      </div>
      <div>
        <%= label_tag :status %>
        <%=select_tag "status", options_for_select([ "created", "started","stopped","completed" ], @project.status) %>
      </div>
      <div>
        <%= label_tag "estimate Effort" %>
        <%= number_field_tag :est_effort, @project.est_effort %>
      </div>

      <div>
        <%= label_tag "actual Effort" %>
        <%= number_field_tag :act_effort, @project.act_effort %>
      </div>


      <%= submit_tag "Save" %>
    <% end %>
</div>

app/views/admin/projects/index.html.erb
  <h1>Projects</h1>
  <br>
  <table>
    <thead>
      <tr>
        <th >User Name</th>
        <th >name</th>
        <th >description</th>
        <th >Delete?</th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td class="table-space"><%= project.user.name %></td>
          <td class="table-space"><%= link_to project.name, edit_admin_project_path(project)  %></td>
          <td class="table-space"><%= project.description %></td>
          <td class="table-space">
          <%= form_tag(admin_project_path(project), method: :DELETE) do %>
                  <%= submit_tag "Delete" %>
          <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>  
</div>

app/views/admin/users/index.html.erb
  <h1>Users</h1>
  <br>
  <table>
    <thead>
      <tr>
        <th >Name</th>
        <th >Email</th>
        <th >Delete?</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="table-space"><%= user.name %></td>
          <td class="table-space"><%= user.email %></td>

          <td class="table-space">
          <%= form_tag(admin_user_path(user), method: :DELETE) do %>
                  <%= submit_tag "Delete" %>
          <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>  
</div>

app/views/home/index.html.erb
<div class="container">

	<h1 class="text-center">Welcome</h1>

</div>

app/views/layouts/_navbar.html.erb
<nav>
    <div class="nav-left">
        <div class="header inline"><%= link_to 'HOME IMPROVEMENT', root_path, style: 'text-decoration: none;'%></div>
        <% if current_user %>
            <div class="new_project inline" id="new_project_button">
        <% end %>
        </div>
    </div>
    <div class="nav-right flex-centering"> 
        <% if user_signed_in? %>
            <%=link_to "Sign out",destroy_user_session_path, method:"delete", class:'auth-button flex-centering uppercase', wave: 'light'%>
        <% else %>
            <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class:'auth-button flex-centering uppercase' %>
        <% end %>
    </div>
</nav>

<script>

$(document).ready(function(){
    if(document.getElementById('new_project_button')){
        ReactOnRails.render('NewProject', {newProjectForm: true}, 'new_project_button');
    }
})

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lexop</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello-world-bundle' %>

    <script defer src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script>



  </head>

  <body>
    <div class="container" id="alert_box">
      <p class="notice" style="display:none"><%= notice %></p>
      <p class="alert" style="display:none"><%= alert %></p>
    </div>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<div class="self-centering" style="max-width:800px; margin-top:30px;">
    <%= form_tag(project_path(@project), method: :put) do %>
      <div>
        <%= label_tag :name %>
        <%= text_field_tag :name, @project.name %>
      </div>
      <div>
        <%= label_tag :description %>
        <%= text_field_tag :description, @project.description %>
      </div>
      <div>
        <%= label_tag :type %>
        <%=select_tag "privacy", options_for_select([ "private", "public" ], @project.privacy) %>
      </div>
      <div>
        <%= label_tag :status %>
        <%=select_tag "status", options_for_select([ "created", "started","stopped","completed" ], @project.status) %>
      </div>
      <div>
        <%= label_tag "estimate Effort" %>
        <%= number_field_tag :est_effort, @project.est_effort %>
      </div>

      <div>
        <%= label_tag "actual Effort" %>
        <%= number_field_tag :act_effort, @project.act_effort %>
      </div>

      <%= submit_tag "Save" %>
    <% end %>
</div>

app/views/projects/index.html.erb
<div class="self-centering" style="max-width:800px;">
    <%= redux_store("projectsStore", props:  @projects_json)%>
    <%= react_component("StoreWrapper", props: {}, prerender: false) %>
</div>